---
#
# Tasks and roles for all hosts
#
# - hosts: kinemon
#   gather_facts: no

#   pre_tasks:
#     - import_tasks: tasks/ssh_juggle_port.yml
#       tags:
#         - port

- hosts: workstation
  gather_facts: no
  pre_tasks:
    - include_vars:
        dir: group_vars/chopper
        depth: 1
    - import_tasks: tasks/ssh_juggle_port.yml
      when: ansible_connection != 'local'
      tags:
        - port

- hosts: workstation
  become: yes
  roles:
    #
    # Basics
    #
    - role: system
      tags:
        - system

    - role: pyenv
      when: enable_pyenv | default(False)
      tags:
        - pyenv

    - role: go
      tags:
        - go

    - role: lsp
      when: enable_nvim_lsp | default(False)
      tags:
        - lsp

    - role: docker
      tags:
        - docker

    - role: neovim
      tags:
        - neovim

    - role: i3-color
      tags:
        - i3color

    # Use auto script
    # - role: nix
    #   tags: 
    #     - system
    #     - package
    #   when: enable_nix | default(False)

    #
    # Security
    #
    - role: security/fail2ban
      tags:
      - fail2ban

    - role: security/iptables
      tags:
      - iptables
      when: enable_iptables

    # - role: geerlingguy.security
    #   tags:
    #     - security
    #
    # System
    #
    - role: containers/system/portainer
      become: no
      tags:
        - containers
      when: enable_portainer | default(False)
    #
    # Virtualization
    #
    - role: virtualization
      become: yes
      tags:
        - virtualization
        - system
      when: enable_virtualization | default(False)

    - role: backups
      tags:
        - backups
        - restic

    - role: fonts
      tags:
        - fonts

    - role: flatpak
      tags:
        - install
        - flatpak
