---
- name: Gather package facts
  package_facts:
    manager: auto

- include_tasks: essential.yml
- include_tasks: remove_snaps.yml
- include_tasks: user.yml
- include_tasks: dotfiles.yml
- include_tasks: packages.yml
