---

go_download_url: "https://go.dev/dl/go1.21.1.linux-amd64.tar.gz"

gdu_package_url: "github.com/dundee/gdu/v5/cmd/gdu@latest"

go_applications:
  - lf
  - smug
  - glow
  - pomo
  - vhs
  - gopls
  - gdu
  - pet
  # - gitty # useful for gitub, gitlab, gitea
  # - hugo # installed with package manager
