---

go_download_url: "https://go.dev/dl/go1.21.1.linux-amd64.tar.gz"

go_applications:
  - lf
  - smug
  - glow
  - pomo
  - vhs
  # - gitty # useful for gitub, gitlab, gitea
  # - hugo # installed with package manager
